
/* Drop Tables */

DROP TABLE IF EXISTS INV_PARTICIPACION_GRUPOS;
DROP TABLE IF EXISTS INV_ROLES;
DROP TABLE IF EXISTS INV_PARTICIPACION_PRODUCTOS;
DROP TABLE IF EXISTS INV_PARTICIPACIONES_PROYECTOS;
DROP TABLE IF EXISTS INV_LOGIN_USUARIO;
DROP TABLE IF EXISTS DOCENTES;
DROP TABLE IF EXISTS INV_PRODUCTOS;
DROP TABLE IF EXISTS INV_SUBTIPO_PRODUCTOS;
DROP TABLE IF EXISTS INV_TIPO_PRODUCTOS;
DROP TABLE IF EXISTS INV_FINANCIACION;
DROP TABLE IF EXISTS INV_PROYECTOS;
DROP TABLE IF EXISTS INV_SUBLINEA_GRUPOS;
DROP TABLE IF EXISTS INV_INFORMES;
DROP TABLE IF EXISTS INV_GRUPOS;
DROP TABLE IF EXISTS INV_PARTICIPANTES_EXTERNOS;
DROP TABLE IF EXISTS INV_CONVOCATORIAS;
DROP TABLE IF EXISTS INV_SUBLINEAS;
DROP TABLE IF EXISTS INV_LINEAS;
DROP TABLE IF EXISTS INV_ENTIDADES;
DROP TABLE IF EXISTS PERSONAS;
DROP TABLE IF EXISTS INV_PERIODOS_ACADEMICOS;
DROP TABLE IF EXISTS INV_TIPO_GRUPOS;




/* Create Tables */

CREATE TABLE INV_ROLES
(
	ID_INV_ROL int NOT NULL,
	NOMBRE_ROL varchar(50) NOT NULL,
	PRIMARY KEY (ID_INV_ROL)
) WITHOUT OIDS;


CREATE TABLE DOCENTES
(
	IDENTIFICACION_DOCENTE varchar NOT NULL,
	NOMBRE varchar NOT NULL,
	PRIMARY KEY (IDENTIFICACION_DOCENTE)
) WITHOUT OIDS;


CREATE TABLE INV_TIPO_PRODUCTOS
(
	ID_TIPO_PRODUCTO int NOT NULL,
	NOMBRE_TIPO_PRODUCTO text NOT NULL,
	DESCRIPCION_TIPO_PRODUCTO text NOT NULL,
	PRIMARY KEY (ID_TIPO_PRODUCTO)
) WITHOUT OIDS;


CREATE TABLE INV_GRUPOS
(
	CODIGO_GRUPO int NOT NULL,
	ID_TIPO int NOT NULL,
	NOMBRE_GRUPO varchar NOT NULL CHECK (nombre_grupo = upper (nombre_grupo)),
	DIRECTOR_GRUPO varchar NOT NULL,
	UNIDAD_ACADEMICA varchar NOT NULL,
	CATEGORIA varchar NOT NULL,
	DESCRIPCION varchar(100) NOT NULL,
	ANO_CREACION date NOT NULL,
	EMAIL varchar(30) NOT NULL,
	TELEFONO varchar(20) NOT NULL,
	DIRECCION_GRUPO varchar(50) NOT NULL,
	PAGINA_WEB text NOT NULL,
	RUTA_AFICHE varchar NOT NULL,
	IMAGEN1 box NOT NULL,
	IMAGEN2 bytea NOT NULL,
	LINK_GRUPLAC text NOT NULL,
	LOGO_GRUPO bytea NOT NULL,
	PRIMARY KEY (CODIGO_GRUPO)
) WITHOUT OIDS;


CREATE TABLE INV_PARTICIPANTES_EXTERNOS
(
	IDENTIFICACION_EXTERNO varchar(50) NOT NULL,
	NOMBRE1 varchar(50) NOT NULL,
	NOMBRE2 varchar(50),
	APELLIDO1 varchar(50) NOT NULL,
	APELLIDO2 varchar(50),
	PROFESION varchar(50) NOT NULL,
	EMAIL varchar(60) NOT NULL,
	TELEFONO varchar(20) NOT NULL,
	FOTO text,
	PRIMARY KEY (IDENTIFICACION_EXTERNO)
) WITHOUT OIDS;


CREATE TABLE INV_PARTICIPACIONES_PROYECTOS
(
	CODIGO_PROYECTO int NOT NULL,
	IDENTIFICACION_DOCENTE varchar NOT NULL,
	IDENTIFICACION_PERSONA varchar NOT NULL,
	IDENTIFICACION_EXTERNO varchar(50) NOT NULL,
	DEDICACION_TIEMPO varchar NOT NULL
) WITHOUT OIDS;


CREATE TABLE INV_CONVOCATORIAS
(
	NUMERO_CONVOCATORIA varchar NOT NULL,
	ESTADO varchar NOT NULL,
	TITULO_CONVOCATORIA varchar NOT NULL,
	FECHA_APERTURA date NOT NULL,
	FECHA_CIERRE date NOT NULL,
	CUANTIA int,
	DESCRIPCION_CONVOCATORIA varchar(1000) NOT NULL,
	EMAIL varchar(50) NOT NULL,
	TELEFONO_CONTACTO varchar(20) NOT NULL,
	PAGINA_CONVOCATORIA text NOT NULL,
	URL_CONVOCATORIA text NOT NULL,
	ARCHIVO_CONVOCATORIA text,
	CONVOCATORIA_DIRIGIDA varchar(60) NOT NULL,
	PRIMARY KEY (NUMERO_CONVOCATORIA)
) WITHOUT OIDS;


CREATE TABLE INV_LINEAS
(
	ID_LINEAS int NOT NULL,
	NOMBRE_LINEA varchar NOT NULL,
	DEFINICION_LINEA varchar(50) NOT NULL,
	OBJETIVO_ESTUDIO varchar(100) NOT NULL,
	OBJETIVOS varchar(100),
	RUTA_ARCHIVO text NOT NULL,
	COORDINADOR_LINEA varchar(50) NOT NULL,
	PRIMARY KEY (ID_LINEAS)
) WITHOUT OIDS;


CREATE TABLE INV_PROYECTOS
(
	CODIGO_PROYECTO int NOT NULL,
	ID_SUBLINEAS int NOT NULL,
	CODIGO_GRUPO int NOT NULL,
	NUMERO_CONVOCATORIA varchar NOT NULL,
	NOMBRE_PROYECTO text NOT NULL,
	OBJETIVO_GENERAL varchar(70) NOT NULL,
	ARCHIVO_ACTAINICIO text NOT NULL,
	ARCHIVO_PROPUESTA text NOT NULL,
	INFORME_FINAL varchar(100) NOT NULL,
	FECHA_PROYECTO date NOT NULL,
	SUBLINEA_AUXILIAR varchar(50),
	GRUPO_AUXILIAR text,
	ESTADO_PROYECTO varchar(30) NOT NULL,
	ESTADO_FINANCIAMIENTO varchar(50) NOT NULL,
	PRIMARY KEY (CODIGO_PROYECTO)
) WITHOUT OIDS;


CREATE TABLE INV_SUBLINEAS
(
	ID_SUBLINEAS int NOT NULL,
	ID_LINEAS int NOT NULL,
	NOMBRE_SUBLINEA text NOT NULL,
	ESTADO varchar(30) NOT NULL,
	DESCRIPCION text NOT NULL,
	PRIMARY KEY (ID_SUBLINEAS)
) WITHOUT OIDS;


CREATE TABLE INV_SUBLINEA_GRUPOS
(
	CODIGO_GRUPO int NOT NULL,
	ID_SUBLINEAS int NOT NULL
) WITHOUT OIDS;


CREATE TABLE INV_ENTIDADES
(
	NIT_ENTIDAD varchar(30) NOT NULL,
	NOMBRE_EMPRESA varchar NOT NULL,
	DESCRIPCION varchar(100),
	SECTOR varchar(50),
	EMAIL varchar(50),
	PAGINAWEB text NOT NULL,
	REPRESENTANTE_LEGAL varchar(50) NOT NULL,
	TELEFONO varchar(20) NOT NULL,
	CELULAR varchar(20) NOT NULL,
	LOGO_EMPRESA varchar(0) NOT NULL,
	PRIMARY KEY (NIT_ENTIDAD)
) WITHOUT OIDS;


CREATE TABLE INV_FINANCIACION
(
	CODIGO_PROYECTO int NOT NULL,
	NIT_ENTIDAD varchar(30) NOT NULL,
	FECHA date NOT NULL,
	VALOR_FINANCIADO decimal,
	DESCRIPCION varchar(100) NOT NULL
) WITHOUT OIDS;


CREATE TABLE INV_PRODUCTOS
(
	CODIGO_PRODUCTO  NOT NULL,
	CODIGO_GRUPO int NOT NULL,
	ID_SUBLINEAS int NOT NULL,
	ID_SUBTIPO_PRODUCTO int NOT NULL,
	NOMBRE_PRODUCTO text NOT NULL,
	OBSERVACIONES varchar NOT NULL,
	FECHA date,
	RECONOCIMIENTO_PRODUCTO varchar(100) NOT NULL,
	SOPORTE text NOT NULL,
	OBSERVACIONES_SOPORTE varchar(200) NOT NULL,
	TIPO_SOPORTE varchar(50) NOT NULL,
	ENTIDAD varchar(100),
	PRIMARY KEY (CODIGO_PRODUCTO)
) WITHOUT OIDS;


CREATE TABLE PERSONAS
(
	IDENTIFICACION_PERSONA varchar NOT NULL,
	NOMBRE varchar NOT NULL,
	PRIMARY KEY (IDENTIFICACION_PERSONA)
) WITHOUT OIDS;


CREATE TABLE INV_PARTICIPACION_GRUPOS
(
	ID_INV_ROL int NOT NULL,
	IDENTIFICACION_PERSONA varchar NOT NULL,
	IDENTIFICACION_DOCENTE varchar NOT NULL,
	IDENTIFICACION_EXTERNO varchar(50) NOT NULL,
	CODIGO_GRUPO int NOT NULL
) WITHOUT OIDS;


CREATE TABLE INV_PARTICIPACION_PRODUCTOS
(
	CODIGO_PRODUCTO  NOT NULL,
	IDENTIFICACION_EXTERNO varchar(50) NOT NULL,
	IDENTIFICACION_PERSONA varchar NOT NULL,
	IDENTIFICACION_DOCENTE varchar NOT NULL,
	CODIGO_GRUPO int NOT NULL
) WITHOUT OIDS;


CREATE TABLE INV_INFORMES
(
	CODIGO_GRUPO int NOT NULL,
	CODIGO_PERIODO int NOT NULL,
	DESCRIPCION text NOT NULL,
	TITULO varchar(100) NOT NULL
) WITHOUT OIDS;


CREATE TABLE INV_PERIODOS_ACADEMICOS
(
	CODIGO_PERIODO int NOT NULL,
	ANO varchar(4) NOT NULL,
	PERIODO varchar(2) NOT NULL,
	FECHA_INICIO varchar(20) NOT NULL,
	FECHA_FIN varchar(20) NOT NULL,
	PRIMARY KEY (CODIGO_PERIODO)
) WITHOUT OIDS;


CREATE TABLE INV_SUBTIPO_PRODUCTOS
(
	ID_SUBTIPO_PRODUCTO int NOT NULL,
	ID_TIPO_PRODUCTO int NOT NULL,
	NOMBRE_SUBTIPO_PRODUCTO varchar(100) NOT NULL,
	DESCRIPCION_SUBTIPO_PRODUCTO text NOT NULL,
	PRIMARY KEY (ID_SUBTIPO_PRODUCTO)
) WITHOUT OIDS;


CREATE TABLE INV_LOGIN_USUARIO
(
	IDENTIFICACION_DOCENTE varchar NOT NULL,
	CLAVE varchar(50) NOT NULL
) WITHOUT OIDS;


CREATE TABLE INV_TIPO_GRUPOS
(
	TIPO_GRUPO varchar(50) NOT NULL,
	ID_TIPO int NOT NULL,
	PRIMARY KEY (ID_TIPO)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE INV_PARTICIPACION_GRUPOS
	ADD FOREIGN KEY (ID_INV_ROL)
	REFERENCES INV_ROLES (ID_INV_ROL)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PARTICIPACION_GRUPOS
	ADD FOREIGN KEY (IDENTIFICACION_DOCENTE)
	REFERENCES DOCENTES (IDENTIFICACION_DOCENTE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PARTICIPACION_PRODUCTOS
	ADD FOREIGN KEY (IDENTIFICACION_DOCENTE)
	REFERENCES DOCENTES (IDENTIFICACION_DOCENTE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PARTICIPACIONES_PROYECTOS
	ADD FOREIGN KEY (IDENTIFICACION_DOCENTE)
	REFERENCES DOCENTES (IDENTIFICACION_DOCENTE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_LOGIN_USUARIO
	ADD FOREIGN KEY (IDENTIFICACION_DOCENTE)
	REFERENCES DOCENTES (IDENTIFICACION_DOCENTE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_SUBTIPO_PRODUCTOS
	ADD FOREIGN KEY (ID_TIPO_PRODUCTO)
	REFERENCES INV_TIPO_PRODUCTOS (ID_TIPO_PRODUCTO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PRODUCTOS
	ADD FOREIGN KEY (CODIGO_GRUPO)
	REFERENCES INV_GRUPOS (CODIGO_GRUPO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PROYECTOS
	ADD FOREIGN KEY (CODIGO_GRUPO)
	REFERENCES INV_GRUPOS (CODIGO_GRUPO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_SUBLINEA_GRUPOS
	ADD FOREIGN KEY (CODIGO_GRUPO)
	REFERENCES INV_GRUPOS (CODIGO_GRUPO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PARTICIPACION_GRUPOS
	ADD FOREIGN KEY (CODIGO_GRUPO)
	REFERENCES INV_GRUPOS (CODIGO_GRUPO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PARTICIPACION_PRODUCTOS
	ADD FOREIGN KEY (CODIGO_GRUPO)
	REFERENCES INV_GRUPOS (CODIGO_GRUPO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_INFORMES
	ADD FOREIGN KEY (CODIGO_GRUPO)
	REFERENCES INV_GRUPOS (CODIGO_GRUPO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PARTICIPACION_GRUPOS
	ADD FOREIGN KEY (IDENTIFICACION_EXTERNO)
	REFERENCES INV_PARTICIPANTES_EXTERNOS (IDENTIFICACION_EXTERNO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PARTICIPACION_PRODUCTOS
	ADD FOREIGN KEY (IDENTIFICACION_EXTERNO)
	REFERENCES INV_PARTICIPANTES_EXTERNOS (IDENTIFICACION_EXTERNO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PARTICIPACIONES_PROYECTOS
	ADD FOREIGN KEY (IDENTIFICACION_EXTERNO)
	REFERENCES INV_PARTICIPANTES_EXTERNOS (IDENTIFICACION_EXTERNO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PROYECTOS
	ADD FOREIGN KEY (NUMERO_CONVOCATORIA)
	REFERENCES INV_CONVOCATORIAS (NUMERO_CONVOCATORIA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_SUBLINEAS
	ADD FOREIGN KEY (ID_LINEAS)
	REFERENCES INV_LINEAS (ID_LINEAS)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_FINANCIACION
	ADD FOREIGN KEY (CODIGO_PROYECTO)
	REFERENCES INV_PROYECTOS (CODIGO_PROYECTO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PARTICIPACIONES_PROYECTOS
	ADD FOREIGN KEY (CODIGO_PROYECTO)
	REFERENCES INV_PROYECTOS (CODIGO_PROYECTO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PROYECTOS
	ADD FOREIGN KEY (ID_SUBLINEAS)
	REFERENCES INV_SUBLINEAS (ID_SUBLINEAS)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_SUBLINEA_GRUPOS
	ADD FOREIGN KEY (ID_SUBLINEAS)
	REFERENCES INV_SUBLINEAS (ID_SUBLINEAS)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PRODUCTOS
	ADD FOREIGN KEY (ID_SUBLINEAS)
	REFERENCES INV_SUBLINEAS (ID_SUBLINEAS)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_FINANCIACION
	ADD FOREIGN KEY (NIT_ENTIDAD)
	REFERENCES INV_ENTIDADES (NIT_ENTIDAD)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PARTICIPACION_PRODUCTOS
	ADD FOREIGN KEY (CODIGO_PRODUCTO)
	REFERENCES INV_PRODUCTOS (CODIGO_PRODUCTO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PARTICIPACION_GRUPOS
	ADD FOREIGN KEY (IDENTIFICACION_PERSONA)
	REFERENCES PERSONAS (IDENTIFICACION_PERSONA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PARTICIPACION_PRODUCTOS
	ADD FOREIGN KEY (IDENTIFICACION_PERSONA)
	REFERENCES PERSONAS (IDENTIFICACION_PERSONA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PARTICIPACIONES_PROYECTOS
	ADD FOREIGN KEY (IDENTIFICACION_PERSONA)
	REFERENCES PERSONAS (IDENTIFICACION_PERSONA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_INFORMES
	ADD FOREIGN KEY (CODIGO_PERIODO)
	REFERENCES INV_PERIODOS_ACADEMICOS (CODIGO_PERIODO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_PRODUCTOS
	ADD FOREIGN KEY (ID_SUBTIPO_PRODUCTO)
	REFERENCES INV_SUBTIPO_PRODUCTOS (ID_SUBTIPO_PRODUCTO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INV_GRUPOS
	ADD FOREIGN KEY (ID_TIPO)
	REFERENCES INV_TIPO_GRUPOS (ID_TIPO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



